### ISSUE TITLE
cern-root-mode can't build on doom emacs 28.1

### ISSUE THREAD

**Issue by yonghuier** [jaypmorgan/root-mode#4]
Message: Symbol's value as variable is void
    Details: (org-src-lang-modes)
    Backtrace:
      (member '("cern-root" . c++) org-src-lang-modes)
      (if (member '("cern-root" . c++) org-src-lang-modes) org-src-lang-modes (setq org-src-lang-modes (cons '("cern-root" . c++) org-src-lang-mod...
      (load-with-code-conversion "/Users/wyh/.emacs.d/.local/straight/build-28.1/cern-root-mode/cern-root-mode-autoloads.el" "/Users/wyh/.emacs.d/...
      (load "/Users/wyh/.emacs.d/.local/straight/build-28.1/cern-root-mode/cern-root-mode-autoloads.el" nil nomessage)
      (progn (load autoloads-file nil 'nomessage))
      (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomessage)))
      (let ((autoloads-file (straight--autoloads-file package))) (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomessage))))
      (straight--load-package-autoloads "cern-root-mode")
      (let ((name (symbol-name package))) (add-to-list 'load-path (directory-file-name (straight--build-dir name))) (straight--load-package-autolo...
      (let ((package (car --dolist-tail--))) (straight-register-package package) (let ((name (symbol-name package))) (add-to-list 'load-path (dire...
      (while --dolist-tail-- (let ((package (car --dolist-tail--))) (straight-register-package package) (let ((name (symbol-name package))) (add-t...
      (let ((--dolist-tail-- (cl-delete-duplicates packages :test #'equal))) (while --dolist-tail-- (let ((package (car --dolist-tail--))) (straig...

**Comment by jaypmorgan** [comment]
As cern-root-mode also provides functionality for the org-mode source code blocks, it requires org/org-babel to have already been loaded otherwise this variable doesn't exist. Can you try loading org first?

**Comment by jaypmorgan** [comment]
I've changed how this variable is set to wait until org-mode is loaded.

**Comment by yonghuier** [comment]
Thanks, but it no effect.  However, I build success by (require 'cern-root-mode), not is (use-package).
